#!/usr/bin/env node
/* Procedural torn-paper masks for assets/css/site.css.

   Two ways to use it (no dependencies either way):
   - open _tools/tear-tuner.html in a browser: presets, sliders, live preview,
     and a Copy button for the CSS block;
   - or run `node _tools/tear-masks.js` to print the block for DEFAULTS.
   Paste the block over the lines between the "generated by _tools/tear-masks.js"
   markers in site.css.

   Each mask is a tiny SVG: a rect filled with a gradient (opaque paper -> torn
   edge) plus noise added to it and hard-thresholded, which gives the ragged grit
   of the Canva tear. "grain" is the coarse bite noise, "grit" a much finer noise
   blended into it, "mod" a very slow noise that makes the tear bite deeper in
   some places than others. Three frames are rendered per direction; they share
   the speckle but each is nudged by a different low-frequency displacement
   ("boil"), and site.css steps through them. The SVGs have no intrinsic size,
   so `mask-size: 100% <h>` lays each one across the full width without repeating. */

(function (root) {
  'use strict';

  var DEFAULTS = {
    grain: { type: 'fractalNoise', freq: [0.12, 0.25], octaves: 2, seed: 3 },
    grit: { on: true, type: 'fractalNoise', freq: [0.55, 0.8], octaves: 2, seed: 7, mix: 0.55 },
    threshold: { offset: -0.55, slope: 30 },
    mod: { on: true, freq: [0.012, 0.04], octaves: 1, seed: 5, amount: 0.3 },
    boil: { freq: [0.03, 0.05], scale: 3, seeds: [1, 2, 3] },
    /* stop offsets are fractions of the 45px band; alpha ~.57 gives roughly two-thirds coverage */
    profile: {
      bottom: [[0.7, 1], [0.78, 0.58], [0.9, 0.56], [1, 0.3]],   /* only the last 10px of the band show */
      top: [[0.4, 1], [0.52, 0.6], [0.92, 0.57], [1, 0.25]]      /* the first 22px of the band show */
    }
  };

  var DIRS = {
    b: { grad: "x1='0' y1='0' x2='0' y2='100%'", profile: 'bottom', swap: false },
    t: { grad: "x1='0' y1='100%' x2='0' y2='0'", profile: 'top', swap: false },
    l: { grad: "x1='100%' y1='0' x2='0' y2='0'", profile: 'top', swap: true },
    r: { grad: "x1='0' y1='0' x2='100%' y2='0'", profile: 'top', swap: true }
  };

  function freq(f, swap) { return (swap ? [f[1], f[0]] : f).join(' '); }
  function turb(o, swap, seed, result) {
    return "<feTurbulence type='" + (o.type || 'fractalNoise') + "' baseFrequency='" + freq(o.freq, swap) +
      "' numOctaves='" + o.octaves + "' seed='" + seed + "' result='" + result + "'/>";
  }

  function svg(p, dir, frame) {
    var d = DIRS[dir], swap = d.swap;
    var stops = p.profile[d.profile].map(function (s) { return "<stop offset='" + s[0] + "' stop-color='#fff' stop-opacity='" + s[1] + "'/>"; }).join('');
    var rect = swap ? "x='-10' y='-5%' width='150%' height='110%'" : "x='-5%' y='-10' width='110%' height='150%'";
    var f = turb(p.grain, swap, p.grain.seed, 'n');
    var noise = 'n';
    if (p.grit && p.grit.on) {
      f += turb(p.grit, swap, p.grit.seed, 'g');
      f += "<feComposite in='n' in2='g' operator='arithmetic' k2='" + p.grit.mix + "' k3='" + +(1 - p.grit.mix).toFixed(4) + "' result='n2'/>";
      noise = 'n2';
    }
    f += "<feComposite in='SourceGraphic' in2='" + noise + "' operator='arithmetic' k2='1' k3='1' k4='" + p.threshold.offset + "' result='s'/>";
    if (p.mod && p.mod.on) {
      f += turb(p.mod, swap, p.mod.seed, 'b');
      f += "<feComposite in='s' in2='b' operator='arithmetic' k2='1' k3='" + p.mod.amount + "' k4='" + (-p.mod.amount / 2) + "' result='s'/>";
    }
    var slope = p.threshold.slope, intercept = 0.5 - slope * 0.5; /* hard edge centred on alpha .5 */
    f += "<feComponentTransfer in='s' result='m'><feFuncA type='linear' slope='" + slope + "' intercept='" + intercept + "'/></feComponentTransfer>";
    f += turb(p.boil, swap, p.boil.seeds[frame], 'w');
    f += "<feDisplacementMap in='m' in2='w' scale='" + p.boil.scale + "' xChannelSelector='R' yChannelSelector='G'/>";
    return "<svg xmlns='http://www.w3.org/2000/svg' width='100%' height='100%'>" +
      "<defs><linearGradient id='g' gradientUnits='userSpaceOnUse' " + d.grad + ">" + stops + "</linearGradient>" +
      "<filter id='f' x='0' y='0' width='100%' height='100%'>" + f + "</filter></defs>" +
      "<rect " + rect + " fill='url(#g)' filter='url(#f)'/></svg>";
  }

  function uri(s) { return 'url("data:image/svg+xml,' + s.replace(/%/g, '%25').replace(/#/g, '%23') + '")'; }

  /* -> { css: the lines for site.css, uris: { b: [frame1, frame2, frame3], t: [...], l: [...], r: [...] } } */
  function build(p) {
    var css = '', uris = {};
    Object.keys(DIRS).forEach(function (dir) {
      uris[dir] = [];
      for (var k = 0; k < p.boil.seeds.length; k++) {
        var u = uri(svg(p, dir, k));
        uris[dir].push(u);
        css += '  --tear-' + dir + (k + 1) + ': ' + u + ';\n';
      }
    });
    return { css: css, uris: uris };
  }

  var api = { DEFAULTS: DEFAULTS, build: build, svg: svg, uri: uri };
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = api;
    if (typeof require !== 'undefined' && require.main === module) process.stdout.write(build(DEFAULTS).css);
  } else {
    root.TearMasks = api;
  }
})(typeof window !== 'undefined' ? window : this);
